#!/usr/bin/env bash

shopt -s extglob
set -o errtrace
set -o errexit

wpy_install()
{
  echo '<<< wpy_install_initialize >>>'
  WPY_PATH="$HOME/.wpy"
  WPY_BIN="$WPY_PATH/wpy"
  mkdir -p $WPY_PATH
  curl -s https://raw.githubusercontent.com/mike3dk/wpy/master/wpy > $WPY_BIN
  chmod 755 "$WPY_BIN"
  echo PATH=\$PATH:$WPY_PATH >> "$HOME/.bash_profile"
}

wpy_install "$@"
